### ISSUE TITLE
pqos_init returned 1

### ISSUE THREAD

**Issue by Zplusless** [intel/intel-cmt-cat#279]
Hi everyone,

I'm trying to use pqos python wrapper. The intel-cmt-cat is installed using the lattest source code and the python wrapper is installed following the official tutorial at https://github.com/intel/intel-cmt-cat/wiki/FAQ#how-to-install-libpqos-python-wrapper.

However, pqos-python failed to init and got error bellow
```
API lock initialization error!
Traceback (most recent call last):
  File "/home/aiot/test_app/proj_mediapipe_streaming/test_pqos.py", line 205, in <module>
    p.init("OS")
  File "/home/aiot/.local/lib/python3.9/site-packages/pqos/pqos.py", line 161, in init
    pqos_handle_error('pqos_init', ret)
  File "/home/aiot/.local/lib/python3.9/site-packages/pqos/common.py", line 55, in pqos_handle_error
    raise err
pqos.error.PqosError: ('pqos_init returned 1', 1)
```
I try to run with `sudo`,  but python will not find pqos with `ModuleNotFoundError: No module named 'pqos'`

The python code is in the attachment. 
CPU:Intel(R) Xeon(R) Gold 6330 CPU
PQoS Tool version: 6.0.0

Any guidance is appreciated! Thanks in advance!

**Comment by Zplusless** [comment]
I delete /var/lock/libpqos manually but it makes no difference

**Comment by Zplusless** [comment]
problem solved. The python wrapper should run with sudo. So add sudo during installation in  https://github.com/intel/intel-cmt-cat/wiki/FAQ#how-to-install-libpqos-python-wrapper will work.
